---
abstract: 'My default dzil plugins'
author:
  - 'Glenn Fowler <cebjyre@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.110390'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-CEBJYRE
requires:
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
resources:
  repository: http://github.com/cebjyre/Dist-Zilla-PluginBundle-CEBJYRE
version: 0.0.1
